### ISSUE TITLE
This lab is missing html files from previous exercise completions 

### ISSUE THREAD

**Issue by Louiefigz** [learn-co-curriculum/html5-video-embed-code-along#1]
when i fork and clone this lab, i know its a continuation of the previous labs for exceptional realty but this file was empty.  I had to redo all of the branches and html files before i could begin following the video to do the video embed.

**Comment by AnnJohn** [comment]
this applies to v-000

**Comment by jongrover** [comment]
I will add this code in as well as direct links to the videos from our amazon s3 as public links. Preventing future issues or confusion.

**Comment by jongrover** [comment]
Solved by commit https://github.com/learn-co-curriculum/html5-video-embed-code-along/commit/2c6512ef914cb919c3146e6d8576bc4e1ee6ffe2
