### ISSUE TITLE
No Text Based Supplementary reading to complement the video

### ISSUE THREAD

**Issue by MysticRiver** [learn-co-curriculum/html5-video-embed-code-along#7]
This Code Along does not have a text based version of the video. All the other code alongs have that except for this one. Not everyomne wants to watch the video. Some people function better by reading instread of starting and stopping a video to code along.

Secondly this video uses the command git co, which does not work with the Learn IDE, but it should instead use git checkout.

**Comment by AnnJohn** [comment]
thanks @MysticRiver. Since you raised this issue already, I'm going to close this duplicate one.
