### ISSUE TITLE
Lesson completed -  but still showing as being worked on

### ISSUE THREAD

**Issue by Matthew-Daly** [learn-co-curriculum/html5-video-embed-code-along#8]
Hi,

I completed this lesson and had to do a manual pull request on Github, as I could not get it to submit any other way. Even though it is showing completed on learn.co, it is still showing that I am working on the lesson and does no show green in the lessons bar.

Steps I have taken:

I tried to submit this through my local environment, but it gives me an error message when trying to connect to Github. Though I've gotten a couple of different ones,  the last one was:

Hmm...this doesn't appear to be a Learn lesson. Are you in the right directory?
matthew@matthew-Lenovo-ideapad-310-15ISK:~/Desktop/Dev/html5-video-embed-code-along-v-000$ 

I tried to submit through the IDE and also got an error. 

I've spent a couple of hours on this, so anything you could do to help would be greatly appreciated. 

Matthew

**Comment by gj** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via [a quick edit](http://help.learn.co/improving-learn/contributing-to-lessons/can-i-edit-a-lesson), or bugs with the Learn platform (such as [lights not turning green](help.learn.co/your-learn-account/learn-lights/lights-not-turning-green) or [IDE issues](http://help.learn.co/the-learn-ide)).

This issue would be perfect for the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 🙂
